move:
  ros__parameters:
    plugins:
      - move_bt_node
    waypoints: ["charging_station", "robotics_lab"]
    waypoint_coords:
      charging_station: [0.0, 0.0, 0.0]
      robotics_lab: [3.0, 2.0, 0.0]
